# Generated by Django 4.2.3 on 2023-08-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="manager",
            field=models.CharField(blank=True, max_length=120, verbose_name="Manager"),
        ),
    ]
