# Generated by Django 4.2.3 on 2023-07-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venue",
            name="owner",
        ),
    ]
