# Generated by Django 4.2.3 on 2023-07-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_remove_venue_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venue",
            name="email_address",
        ),
        migrations.RemoveField(
            model_name="venue",
            name="phone",
        ),
    ]
