# Generated by Django 4.2.3 on 2023-08-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_attendance_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="manager",
            field=models.CharField(blank=True, max_length=120, verbose_name="Manager"),
        ),
    ]
