# Generated by Django 4.2.3 on 2023-08-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_remove_venue_email_address_remove_venue_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="exco",
        ),
        migrations.AlterField(
            model_name="student",
            name="chat_id",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
