# Generated by Django 4.2.3 on 2023-08-04 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_venue_email_address_remove_venue_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='chat_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Tracking_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.student')),
            ],
        ),
    ]
