# Generated by Django 4.2.3 on 2023-08-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_remove_membership_exco_alter_student_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cca",
            name="email",
            field=models.CharField(max_length=120, null=True, verbose_name="Email"),
        ),
    ]
