# Generated by Django 4.2.3 on 2023-08-04 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_paymentdetails_paymentpoll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking_payment',
            name='event',
        ),
        migrations.AddField(
            model_name='paymentpoll',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentpoll',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.student'),
        ),
    ]
