# Generated by Django 4.2.3 on 2023-08-05 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_cca_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='manager',
            new_name='attendees',
        ),
    ]
