# Generated by Django 4.2.3 on 2023-08-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_tracking_payment_event_paymentpoll_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentpoll',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='paymentpoll',
            name='student',
        ),
        migrations.AddField(
            model_name='tracking_payment',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
